# .github/workflows/cd-deploy-aks.yml
name: CD - Deploy Backend & Frontend to AKS

on:
  workflow_dispatch:

env:
  AKS_CLUSTER_NAME: week09-aks
  AKS_RESOURCE_GROUP: week09-rg
  ACR_NAME: uroalsaadiweek09acr

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: Production

    outputs:
      PRODUCT_API_IP: ${{ steps.get_product_ip.outputs.external_ip }}
      ORDER_API_IP: ${{ steps.get_order_ip.outputs.external_ip }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        run: |
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} \
                                 --name ${{ env.AKS_CLUSTER_NAME }} \
                                 --overwrite-existing

      - name: Deploy Backend
        run: |
          cd k8s/
          kubectl apply -f configmaps.yaml -n ecommerce
          kubectl apply -f secrets.yaml -n ecommerce
          kubectl apply -f product-db.yaml -n ecommerce
          kubectl apply -f order-db.yaml -n ecommerce
          kubectl apply -f product-service.yaml -n ecommerce
          kubectl apply -f order-service.yaml -n ecommerce

      - name: Wait for Backend LoadBalancer IPs
        run: |
          for i in $(seq 1 60); do
            PRODUCT_IP=$(kubectl get svc product-service-w08e1 -n ecommerce -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            ORDER_IP=$(kubectl get svc order-service-w08e1 -n ecommerce -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [[ -n "$PRODUCT_IP" && -n "$ORDER_IP" ]]; then break; fi
            sleep 5
          done

          if [[ -z "$PRODUCT_IP" || -z "$ORDER_IP" ]]; then
            echo "Error: LoadBalancer IPs not assigned after timeout."
            exit 1
          fi

          echo "PRODUCT_IP=$PRODUCT_IP" >> $GITHUB_ENV
          echo "ORDER_IP=$ORDER_IP" >> $GITHUB_ENV

      - name: Capture Product IP
        id: get_product_ip
        run: echo "external_ip=${{ env.PRODUCT_IP }}" >> $GITHUB_OUTPUT

      - name: Capture Order IP
        id: get_order_ip
        run: echo "external_ip=${{ env.ORDER_IP }}" >> $GITHUB_OUTPUT

      - name: Logout Azure
        if: always()
        run: az logout

  deploy_frontend:
    needs: deploy_backend
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/frontend:latest ./frontend/
          az acr login --name ${{ env.ACR_NAME }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/frontend:latest

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy Frontend to AKS
        run: |
          cd k8s/
          kubectl apply -f frontend.yaml

      - name: Logout Azure
        if: always()
        run: az logout
