name: Backend CI - Build and Push to ACR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Order Service
        run: |
          IMAGE_NAME=order_service
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG ./backend/order_service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Build and Push Product Service
        run: |
          IMAGE_NAME=product_service
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG ./backend/product_service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:$IMAGE_TAG
